spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test #内存模式
#    url: jdbc:log4jdbc:h2:file:.\target\temp\h2\db  # 文件模式
    username: root
    password: 123456
  liquibase:
    change-log: classpath:db/liquibase/changelog-master.xml
    drop-first: false
  h2:
    console:
      # 默认关闭 http://host:port/h2-console (url=jdbc:h2:mem:test / 账号密码=root/test 和上面的datasource配置保持一致)
      enabled: true
      settings:
        # 不开启报错: Sorry, remote connections ('webAllowOthers') are disabled on this server.
        web-allow-others: true